---
title: "The maintenance of deleterious variation in wild Chinese rhesus macaques"
output: html_document
author: "Camille Steux and Zachary A. Szpiech"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setwd, include=FALSE}
#setwd("/Users/cxs6193/Documents/R_analysis/ROH_distribution_5pop")
#setwd("/media/camille/Donnees/Documents/Doctorat/Zach_paper/Ranalysis")
setwd("/home/csteux/Documents/Zach_paper_27-02-24/Ranalysis")
```

```{r packages, message=FALSE, warning=FALSE}
#Importing packages
library(ggplot2)
library(gridExtra)
library(tidyverse)
library(ggpubr)
library(grid)
library(dplyr)
library(knitr)
```

### **ROH distribution analysis**

#### Importing data (ROH length and number per individuals)

```{r importdata, echo=FALSE, message=FALSE, warning=FALSE, fig.align = 'center', fig.dim=c(10,7), unit=cm}
#Importing data
data <- read.table("5pop_roh_summary.txt", header=TRUE, sep="\ ",stringsAsFactors = TRUE)
kable(data[1:10,])
```

#### Plotting data

##### 1. SROH distribution per population

```{r plotSROH, echo=FALSE, message=FALSE, warning=FALSE}
#Setting legend colors so it matches Liu. et al (2017) paper
leg <- c("mulatta" = "chartreuse3","lasiotis" = "orchid3", "brevicaudus" = "darkorange", "littoralis" = "red2", "tcheliensis" = "blue3")
pop_order <- factor(data$pop, level=c('mulatta', 'lasiotis', 'brevicaudus', 'littoralis','tcheliensis'))

#Plots
plotAll1 <- ggplot(data = data, mapping=aes(x=pop_order, y=TOTAL/(1e6), colour=pop_order, fill=pop_order)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), show.legend = FALSE) + 
  geom_point(show.legend = FALSE) +
  #stat_compare_means(comparisons = my_comparisons, label.y = c(57, 57, 57, 83, 63, 78, 103, 72, 95, 89), label = "p.signif", method = "t.test", size = 2.5) +
  labs(x = "Population", y = "SROH (Mb)", title ="A") +
  scale_colour_manual(values = leg) +
  scale_fill_manual(values = alpha(leg, .3)) +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "black", size = 12, angle = 35, hjust = 1, face = "italic"), axis.title.x=element_blank(), axis.text.y = element_text(size=10, color = "black"), axis.title.y=element_text(size=14, margin = unit(c(0, 0.5, 0,0), "cm")), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = c(.12, .85), legend.title = element_text(size=14), legend.text = element_text(size=11), legend.key.height = unit(0.35, 'cm'), plot.title = element_text(size= 15), plot.margin = unit(c(0.2, 1, 0.2, 0.75), "cm"), axis.ticks = element_line(color = "black"), axis.line = element_line(color = "black")) 
#plot(plotAll1)

plotA1 <- ggplot(data = data, mapping=aes(x=pop_order, y=A/(1e6), colour=pop_order, fill=pop_order)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), show.legend = FALSE) + 
  geom_point(show.legend = FALSE) +
  #stat_compare_means(comparisons = my_comparisons, label.y = c(57, 57, 57, 83, 63, 78, 103, 72, 95, 89), label = "p.signif", method = "t.test", size = 2.5) +
  labs(x = "Population", y = "SROH (Mb)", title ="B") +
  scale_colour_manual(values = leg) +
  scale_fill_manual(values = alpha(leg, .3)) +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "black", size = 12, angle = 35, hjust = 1, face = "italic"), axis.title.x=element_blank(), axis.text.y = element_text(size=10, color = "black"), axis.title.y=element_text(size=14, margin = unit(c(0, 0.5, 0,0), "cm")), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = c(.12, .85), legend.title = element_text(size=14), legend.text = element_text(size=11), legend.key.height = unit(0.35, 'cm'), plot.title = element_text(size= 15), plot.margin = unit(c(0.2, 1, 0.2, 0.75), "cm"), axis.ticks = element_line(color = "black"), axis.line = element_line(color = "black")) 
#plot(plotAll1)

plotB1 <- ggplot(data = data, mapping=aes(x=pop_order, y=B/(1e6), colour=pop_order, fill=pop_order)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), show.legend = FALSE) + 
  geom_point(show.legend = FALSE) +
  #stat_compare_means(comparisons = my_comparisons, label.y = c(57, 57, 57, 83, 63, 78, 103, 72, 95, 89), label = "p.signif", method = "t.test", size = 2.5) +
  labs(x = "Population", y = "SROH (Mb)", title ="C") +
  scale_colour_manual(values = leg) +
  scale_fill_manual(values = alpha(leg, .3)) +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "black", size = 12, angle = 35, hjust = 1, face = "italic"), axis.title.x=element_blank(), axis.text.y = element_text(size=10, color = "black"), axis.title.y=element_text(size=14, margin = unit(c(0, 0.5, 0,0), "cm")), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = c(.12, .85), legend.title = element_text(size=14), legend.text = element_text(size=11), legend.key.height = unit(0.35, 'cm'), plot.title = element_text(size= 15), plot.margin = unit(c(0.2, 1, 0.2, 0.75), "cm"), axis.ticks = element_line(color = "black"), axis.line = element_line(color = "black")) 
#plot(plotAll1)

plotC1 <- ggplot(data = data, mapping=aes(x=pop_order, y=C/(1e6), colour=pop_order, fill=pop_order)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), show.legend = FALSE) + 
  geom_point(show.legend = FALSE) +
  #stat_compare_means(comparisons = my_comparisons, label.y = c(57, 57, 57, 83, 63, 78, 103, 72, 95, 89), label = "p.signif", method = "t.test", size = 2.5) +
  labs(x = "Population", y = "SROH (Mb)", title ="D") +
  scale_colour_manual(values = leg) +
  scale_fill_manual(values = alpha(leg, .3)) +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "black", size = 12, angle = 35, hjust = 1, face = "italic"), axis.title.x=element_blank(), axis.text.y = element_text(size=10, color = "black"), axis.title.y=element_text(size=14, margin = unit(c(0, 0.5, 0,0), "cm")), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = c(.12, .85), legend.title = element_text(size=14), legend.text = element_text(size=11), legend.key.height = unit(0.35, 'cm'), plot.title = element_text(size= 15), plot.margin = unit(c(0.2, 1, 0.2, 0.75), "cm"), axis.ticks = element_line(color = "black"), axis.line = element_line(color = "black")) 
#plot(plotAll1)

#Plotting and saving
ROHlength <- grid.arrange(plotAll1, plotA1, plotB1, plotC1, ncol=2)
#ggsave("Total_length_ROH.png", plot = ROHlength, width = 25, height = 29, units = "cm")

#cairo_ps(file = "Total_length_ROH.eps", onefile = FALSE, width=9.8, height=11.4)
#plot(ROHlength)
#dev.off()
```

##### 2. NROH vs SROH

```{r srohnrohplot, echo = FALSE}
#Setting legend colors so it matches Liu. et al (2017) paper
leg <- c("mulatta" = "chartreuse3","lasiotis" = "orchid3", "brevicaudus" = "darkorange", "littoralis" = "red2", "tcheliensis" = "blue3")

ggplot(data) +
  geom_point(mappin=aes(x=TOTAL/(1e6),y=nTOTAL,colour=pop), size = 2.5) + 
  labs(x = "SROH (in Mb)", y = "NROH", title ="", fill="Population") +
  scale_colour_manual(values = leg, name="Subspecies") +
  theme_light() +
  theme(axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16), axis.text = element_text(size = 14, color = "black"), axis.ticks = element_line(color = "black"), plot.title = element_blank(), legend.position = c(.82, .23), legend.title = element_text(size=16), legend.text = element_text(size=14,face = 'italic'), legend.key.height = unit(0.4, 'cm'), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), panel.border = element_blank(), legend.background = element_blank(), legend.box.background = element_rect(colour = "black")) +
  coord_cartesian(ylim=c(0,max(data$nTOTAL)), xlim=c(0,max(data$TOTAL/(1e6))))

#ggsave("NROH_vs_SROH.png", width = 15, height = 11, units = "cm")
#dev.off()
#cairo_ps(file = "NROH_vs_SROH.eps", onefile = FALSE, width=5.9, height=4.3)

```

##### 3. Individual ROH genome coverage

Computing ROH coverage.

``` {r genomerohfraction, message=FALSE, warning=FALSE, fig.align = 'center', fig.dim=c(10,6), unit=cm}
options( "digits"=3)
pop <- c("mulatta","lasiotis", "brevicaudus", "littoralis", "tcheliensis")
genome_size=2900000000
data2 <- cbind(rownames(data),data)
colnames(data2) <- c("ind",colnames(data))
data2 <- data2[,c(1,2,4,6,8,10)]
data2[["nonroh"]] <- genome_size-data$TOTAL
data2[["GiA"]] <- data$A/genome_size*100
data2[["GiB"]] <- data$B/genome_size*100
data2[["GiC"]] <- data$C/genome_size*100
data2[["GiR"]] <- data$TOTAL/genome_size*100
rownames(data2) <- NULL

for (p in pop) {
  df <- data2[data2$pop==p,]
  df <- arrange(df, desc(nonroh))
  assign(paste("data2_", p,sep=""),df)
}

data3 <- rbind(data2_mulatta, data2_lasiotis, data2_littoralis, data2_brevicaudus, data2_tcheliensis)
data3$num <- c(1:79)

longer_data <- data3 %>% #formatting data frame  
        pivot_longer(c(A,B,C,nonroh,GiA,GiB,GiC,GiR), names_to = "class", values_to = "length")
longer_data$ind <- factor(longer_data$ind, levels = data3$ind)

kable(data3[1:10,c(1,2,8,9,10,11)], col.names = c("Individual","Population", 'Gi,a' ,'Gi,b','Gi,c','Gi,r'))
```

```{r save plot for paper, echo=FALSE, warning=FALSE, message=FALSE}
legclass <- c("A" = "steelblue4","B" = "steelblue3", "C" = "steelblue2", "nonroh" = "gray80")
legpop = ifelse(data3$pop %in% "mulatta", "chartreuse3", ifelse(data3$pop %in% "lasiotis", "orchid3",  ifelse(data3$pop %in% "littoralis", "red2",  ifelse(data3$pop %in% "brevicaudus", "darkorange",  "blue3"))))
x_tick <- c(5.5,26,55.5,72,77)

# ROH COVERAGE
rohcoverage.plot <- ggplot(longer_data) +
  geom_col(aes(x=num,y=(length*100/genome_size),fill=class, group = pop)) + 
  geom_segment(aes(y = -1, yend=-1, x = 0.55, xend = 79.5), size=0.2) +
  geom_segment(aes(y = -0.5, yend=-1, x = 0.55, xend = 0.55), size=0.2) +
  geom_segment(aes(y = -0.5, yend=-1, x = 10.5, xend = 10.5), size=0.2) +
  geom_segment(aes(y = -0.5, yend=-1, x = 41.5, xend = 41.5), size=0.2) +
  geom_segment(aes(y = -0.5, yend=-1, x = 69.5, xend = 69.5), size=0.2) +
  geom_segment(aes(y = -0.5, yend=-1, x = 74.5, xend = 74.5), size=0.2) +
  geom_segment(aes(y = -0.5, yend=-1, x = 79.5, xend = 79.5), size=0.2) +
  labs(x = "Individuals", y = "Genome coverage (%)", title ="Genome ROH coverage") +
  scale_fill_manual(values = legclass, labels = c("Short ROH","Medium ROH","Long ROH", "Non ROH"), name = "Size class ROH") +
  scale_x_continuous(breaks = x_tick, labels = c("mulatta","lasiotis","littoralis","brevicaudus","tcheliensis")) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 30, hjust=0.95, vjust=0.2, size=10, colour = "black", margin = unit(c(-0.9, 0, 0, 0), "cm"), face = 'italic'), axis.text.y = element_text(size = 10, color = "black"), axis.ticks.y = element_line(color = "black"),  axis.title.y = element_text(size = 12), plot.title = element_blank(), axis.ticks.x=element_blank(), axis.title.x = element_blank(),  panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), legend.text = element_text(size=8), legend.position = c(.169, .875), legend.title = element_blank(), legend.key.height = unit(0.3, 'cm'), legend.key.width = unit(0.5, 'cm'), panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), axis.line.x = element_blank(), panel.border = element_blank(), plot.margin = unit(c(0.2, 0.2, 1, 0.2), "cm")) +
  coord_cartesian(ylim=c(0,30))

#ggsave("ROH_gen_coverage.png", width = 15, height = 9, units = "cm")
rohcoverage.plot

#cairo_ps(file = "ROH_gen_coverage.eps", onefile = FALSE, width=5.5, height=3.54)
#plot(rohcoverage.plot)
#dev.off()

```


